### ISSUE TITLE
Kali-themes install error 

### ISSUE THREAD

**Issue by Trevohack** [xct/kali-clean#12]
**kali-clean** requires this kali package called `kali-themes`. However, I explored some issues while trying so many attempts to install this specific package, is there any possibility for someone to guide me on how to install that package?

![image](https://github.com/xct/kali-clean/assets/136177431/fb9d0ca1-631c-4533-9a49-0a6b528d6975)

**Comment by SpaceShuttleIO** [comment]
If anyone can help pls comment :)

**Comment by clem9669** [comment]
Hi, 
You have a problem prior to installation phase. It seems related to KDE (xdg plasma-workspace).

Investigate in this direction.
Cheers

**Comment by Trevohack** [comment]
Hey, Thanks for your response. I had to reinstall Kali's latest version since I had an older version. It worked.
