### ISSUE TITLE
Kali VM freeze on login after installation 

### ISSUE THREAD

**Issue by Zak1sMe** [xct/kali-clean#15]
Hi,

I've tried it on Kali VM for vmware workstation and it freezes.
After selecting i3 and login in, I can only see the wallpaper. No desktop icons, and nothing works including shortcuts (like to start a terminal).

Kindly look into that.

**Comment by clawzed** [comment]
Same issue here

**Comment by clem9669** [comment]
https://www.addictivetips.com/ubuntu-linux-tips/beginners-guide-i3-window-manager/
